name: Deploy to Localhost

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 1: Install dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Step 2: Deploy to Localhost using rsync (bypassing tar)
      - name: Deploy to Localhost via rsync
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            rsync -av --exclude='./node_modules' ./ /mnt/d/Devops/New-2024/demo/testing/github-actions

      # Step 3: Install dependencies and run app on server
      - name: Install dependencies and run app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /mnt/d/Devops/New-2024/demo/testing/github-actions
            npm install
            node index.js

