name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Rename env file
        run: mv env-cp .env

      - name: Upload backend folder
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: .
