name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Rename env file
        run: |
          if [ -f env-cp ]; then mv env-cp .env; fi

      - name: Install Dependencies
        run: npm install

      - name: Run the Backend App
        run: |
          npm run start

